# Generated by Django 5.0.6 on 2024-07-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenfieldtype',
            name='display_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
