# Generated by Django 5.0.6 on 2024-08-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0003_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
