# Generated by Django 5.0.6 on 2024-08-04 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0004_website_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'نوع قاعدة بيانات',
                'verbose_name_plural': 'أنواع قواعد البيانات',
            },
        ),
        migrations.AddField(
            model_name='website',
            name='db_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='v3.dbtype'),
        ),
    ]
