# Generated by Django 5.0.6 on 2024-08-04 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0005_dbtype_website_db_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='db_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='v3.dbtype', unique=True),
        ),
    ]
