# Generated by Django 5.0.6 on 2024-08-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0007_alter_dbtype_name_alter_website_db_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenfieldtype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
