# Generated by Django 5.0.6 on 2024-08-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0008_alter_screenfieldtype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel/')),
            ],
            options={
                'verbose_name': 'قالب اكسل',
                'verbose_name_plural': 'قوالب الاكسل',
            },
        ),
    ]
