# Generated by Django 5.0.6 on 2024-08-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0010_screenfield_bg_color_screenfield_bg_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenfield',
            name='cmd',
            field=models.TextField(blank=True, null=True, verbose_name='الأمر البرمجي'),
        ),
    ]
