# Generated by Django 5.0.6 on 2024-09-21 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_dbfieldtype_display_name_alter_dbfieldtype_name'),
        ('v3', '0012_alter_screenfield_bg_color_alter_screenfield_bg_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreBuiltField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحقل')),
                ('project', models.CharField(blank=True, max_length=200, null=True, verbose_name='المشروع')),
                ('details', models.TextField(verbose_name='وصف الحقل')),
                ('cmd', models.TextField(verbose_name='سطر الأمر')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tool', verbose_name='التقنية / الأداة')),
            ],
            options={
                'verbose_name': 'حقل ',
                'verbose_name_plural': 'مستودع الحقول',
            },
        ),
    ]
