# Generated by Django 5.0.6 on 2024-09-21 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_tool_description'),
        ('v3', '0013_prebuiltfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebuiltfield',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='base.tool', verbose_name='التقنية / الأداة'),
        ),
    ]
