# Generated by Django 5.0.6 on 2024-06-14 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'نوع قاعدة بيانات',
                'verbose_name_plural': 'أنواع قواعد البيانات',
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم قاعدة البيانات')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='website.website')),
                ('db_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.dbtype')),
            ],
            options={
                'verbose_name': 'قاعدة بيانات',
                'verbose_name_plural': 'قواعد البيانات',
            },
        ),
    ]
