# Generated by Django 5.0.6 on 2024-06-14 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('website', '0002_dbtype_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='db_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.dbtype'),
        ),
        migrations.AlterField(
            model_name='database',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='website.website'),
        ),
        migrations.DeleteModel(
            name='DBType',
        ),
    ]
