# Generated by Django 5.0.6 on 2024-06-14 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_dbtype_tool'),
        ('website', '0003_alter_database_db_type_alter_database_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tool'),
        ),
    ]
