# Generated by Django 5.0.6 on 2024-06-14 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_dbtype_tool'),
        ('website', '0004_website_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tool', verbose_name='اللغة / إطار العمل'),
        ),
        migrations.CreateModel(
            name='DbTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='الاسم')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='website.database', verbose_name='قاعدة البيانات')),
            ],
            options={
                'verbose_name': 'جدول',
                'verbose_name_plural': 'جداول قواعد البيانات',
            },
        ),
        migrations.CreateModel(
            name='TableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('db_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='website.dbtable')),
            ],
            options={
                'verbose_name': 'حقل',
                'verbose_name_plural': 'حقول الجداول',
            },
        ),
    ]
