# Generated by Django 5.0.6 on 2024-06-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_websitepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitepage',
            name='code',
        ),
        migrations.AddField(
            model_name='websitepage',
            name='css',
            field=models.TextField(default='', verbose_name='css'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitepage',
            name='html',
            field=models.TextField(default='', verbose_name='html'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitepage',
            name='js',
            field=models.TextField(default='', verbose_name='js'),
            preserve_default=False,
        ),
    ]
