# Generated by Django 5.0.6 on 2024-06-22 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_websitepage_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitepage',
            name='website',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='website.website', verbose_name='الموقع'),
            preserve_default=False,
        ),
    ]
