# Generated by Django 5.0.6 on 2024-06-25 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_websitepage_css_alter_websitepage_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefield',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.fieldtypes'),
        ),
    ]
