# Generated by Django 5.0.6 on 2024-07-05 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_dbfieldtype_display_name_alter_dbfieldtype_name'),
        ('website', '0013_website_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablefield',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.dbfieldtype'),
        ),
    ]
