# Generated by Django 5.0.6 on 2024-07-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_tablefield_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefield',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وضصف الحقل'),
        ),
        migrations.DeleteModel(
            name='FieldTypes',
        ),
    ]
