# Generated by Django 5.0.6 on 2024-07-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_tablefield_description_delete_fieldtypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitepage',
            name='css',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='html',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='js',
        ),
    ]
