# Generated by Django 5.0.6 on 2024-06-14 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'أداة / إطار عمل ', 'verbose_name_plural': 'أدوات / أطر عمل'},
        ),
        migrations.AddField(
            model_name='dbtype',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tool', verbose_name='اللغة / إطار العمل'),
        ),
        migrations.AlterModelTable(
            name='tool',
            table=None,
        ),
    ]
