# Generated by Django 5.0.6 on 2024-06-14 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_tool_options_dbtype_tool_alter_tool_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtype',
            name='tool',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.tool', verbose_name='اللغة / إطار العمل'),
            preserve_default=False,
        ),
    ]
