# Generated by Django 5.0.6 on 2024-07-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_dbfieldtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbfieldtype',
            name='db_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_types', to='base.dbtype'),
        ),
    ]
